name: deltamin
description: Minify your Delta data before sending it down the wire to save bandwidth.
version: 0.1.0
repository: https://github.com/dwyl/deltamin
homepage: https://github.com/dwyl/deltamin

environment:
  sdk: ^3.0.5

dependencies:
  collection: ^1.18.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
